name: CI

on:
    push:
        branches: [main,astro-doc]

jobs:
    # setup:
    #     runs-on: ubuntu-latest
    #     outputs:
    #         cache-hit: ${{ steps.cache-pnpm.outputs.cache-hit }}
    #     steps:
    #         - name: Checkout
    #           uses: actions/checkout@v4.1.1

    #         # 使用 Cache 来存储和恢复 pnpm 依赖项
    #         - name: Cache pnpm dependencies
    #           id: cache-pnpm
    #           uses: actions/cache@v3.3.2
    #           with:
    #               path: |
    #                   ~/.pnpm-store
    #                   **/node_modules
    #               key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
    #               restore-keys: |
    #                   ${{ runner.os }}-pnpm-

    #         - name: Install Node.js
    #           uses: actions/setup-node@v3
    #           with:
    #               node-version: '18.x'

    #         - name: Install pnpm
    #           run: npm install -g pnpm

    #         - name: Install pnpm dependencies
    #           if: steps.cache-pnpm.outputs.cache-hit != 'true'
    #           run: pnpm install

    # build:
    #     needs: setup
    #     runs-on: ubuntu-latest
    #     steps:
    #         - name: Checkout
    #           uses: actions/checkout@v4.1.1

    #         - name: Install Node.js
    #           uses: actions/setup-node@v3
    #           with:
    #               node-version: '18.x'

    #         - name: Install pnpm
    #           run: npm install -g pnpm

    #         - name: Install pnpm dependencies
    #           run: pnpm install

    #         - name: Run build task
    #           run: pnpm run build

    deploy:
        runs-on: ubuntu-latest
        environment: production
        steps:
            - name: Checkout
              uses: actions/checkout@v4.1.1
            # 添加环境变量检查
            - name: Check env
              run: |
                echo "Checking environment variables..."
                # 列出所有环境变量（注意不要打印敏感信息）
                env | grep -v -i "secret" | grep -v -i "token"
              
            - name: Cache Next.js build
              uses: actions/cache@v4
              with:
                  path: |
                      ~/.npm
                      ${{ github.workspace }}/.next/cache
                      # 添加 node_modules 缓存
                      **/node_modules
                  # 优化缓存 key
                  key: ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('**/*.{js,jsx,ts,tsx,mdx}') }}
                  restore-keys: |
                      ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-
                      ${{ runner.os }}-nextjs-
            
            - name: Install Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '18.x'

            - name: Install pnpm
              run: npm install -g pnpm@9.14.4

            - name: Install pnpm dependencies
              run: |
                # 只安装生产依赖
                pnpm --version
                pnpm install --frozen-lockfile --prefer-offline

            - name: Check changes
              id: changes
              run: |
                # 获取当前分支最新的两次提交
                if git rev-parse HEAD^1 >/dev/null 2>&1; then
                  # 如果存在上一次提交，比较最近两次提交的差异
                  git diff --name-only HEAD^1 HEAD > changes.txt
                else
                  # 如果是仓库的第一次提交，获取所有文件
                  git ls-files > changes.txt
                fi
                echo "content_changed=$(grep -q 'sections/' changes.txt && echo 'true' || echo 'false')" >> $GITHUB_OUTPUT

            - name: Run build task
              if: steps.changes.outputs.content_changed == 'true'
              run: pnpm run build
              env:
                NEXT_PUBLIC_BAIDU_TONGJI: ${{ vars.NEXT_PUBLIC_BAIDU_TONGJI }}
                NEXT_PUBLIC_REPO: ${{ vars.NEXT_PUBLIC_REPO }}
                NEXT_PUBLIC_REPOID: ${{ vars.NEXT_PUBLIC_REPOID }}
                NEXT_PUBLIC_CATEGORY: ${{ vars.NEXT_PUBLIC_CATEGORY }}
                NEXT_PUBLIC_CATEGORY_ID: ${{ vars.NEXT_PUBLIC_CATEGORY_ID }}
                NEXT_PUBLIC_MAPPING: ${{ vars.NEXT_PUBLIC_MAPPING }}
                NEXT_PUBLIC_INPUT_POSITION: ${{ vars.NEXT_PUBLIC_INPUT_POSITION }}
                NEXT_PUBLIC_THEME: ${{ vars.NEXT_PUBLIC_THEME }}
                NEXT_PUBLIC_LANG: ${{ vars.NEXT_PUBLIC_LANG }}
                NEXT_PUBLIC_UMAMI: ${{ vars.NEXT_PUBLIC_UMAMI }}
                NEXT_PUBLIC_API_URL: ${{ vars.NEXT_PUBLIC_API_URL }}
                NEXT_PUBLIC_SITE_URL: ${{ vars.NEXT_PUBLIC_SITE_URL }}
                NEXT_PUBLIC_AUTHOR_NAME: ${{ vars.NEXT_PUBLIC_AUTHOR_NAME }}
                NEXT_PUBLIC_SITE_NAME: ${{ vars.NEXT_PUBLIC_SITE_NAME }}
                NEXT_PUBLIC_SITE_DESCRIPTION: ${{ vars.NEXT_PUBLIC_SITE_DESCRIPTION }}
            - name: Deploy to Server
              uses: easingthemes/ssh-deploy@main
              with:
                  SSH_PRIVATE_KEY: ${{ secrets.ALIYUN_SERVER_ACCESS_TOKEN }}
                  ARGS: '-rlgoDzvc -i --delete'
                  SOURCE: 'out/'
                  SCRIPT_BEFORE: |
                      whoami
                      ls -al
                      pwd
                  REMOTE_HOST: ${{ secrets.ALIYUN_SERVER_HOST }}
                  REMOTE_USER: 'root'
                  TARGET: '/opt/1panel/apps/openresty/openresty/www/sites/weekly.mengpeng.tech/index/'
                  EXCLUDE: '/dist/, /node_modules/'
